image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
